### ISSUE TITLE
[keyman.com] Redirect IPA keyboard searches to /ipa landing page

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman.com#37]
From Language Software Community [forum](https://community.software.sil.org/t/cant-find-how-to-type-ipa-pre-nasalized-superscript-nd-usin-new-keyman/2594/6) where a user requested the SIL IPA keyboard to appear higher in keyboard searches

Reply from @mcdurdin 
> These are returned in alphabetical order in the keyboard search.
> I'd like to include a shortcut at the top when one searches for "IPA" with a link to the https://keyman.com/ipa/ page whcih is a dedicated home page for IPA keyboards...

**Comment by darcywong00** [comment]
From a review comment in 38
> I would prefer to see a banner added at the top of the search with a blurb about how we have an IPA landing page. BUT: let's leave this until we've had the language+keyboard search discussion in a few weeks because it may all change again.

**Comment by mcdurdin** [comment]
Also, from https://github.com/keymanapp/api.keyman.com/issues/87#issuecomment-668895608:

- [ ] When searching for ipa, why does IPATotal show up first (with 82 monthly downloads) and IPA (SIL) only second? Especially since I did the search on Linux where IPATotal is not supported. I would have expected IPA (SIL) to show up first.
